FROM continuumio/miniconda3:24.1.2-0

RUN chmod 1777 /tmp

WORKDIR /app

# Copy only the requirements file, to cache the installation of dependencies
COPY requirements.txt /app/requirements.txt

# Copy files
COPY download_model.py /app

# Create a Conda environment
RUN conda create -n docker_env python=3.10 -y

# Activate the Conda environment
SHELL ["conda", "run", "-n", "docker_env", "/bin/bash", "-c"]

# Install PyTorch with CUDA support
# Adjust the PyTorch and CUDA versions as needed
# Check https://pytorch.org/get-started/locally/ for the correct command for your needs
RUN conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia -y

# COPY DESCRIPTIONS
# install dependencies
RUN pip install -r requirements.txt

# Run the download
RUN python /app/download_model.py

# Download everything from NLTK
RUN python -m nltk.downloader punkt

# Expose the port the app runs on
EXPOSE 8000

# Set a default port
ENV PORT=8000

# Copy the rest of your application
COPY . /app

ENV GROBID_URL='https://kermitt2-grobid.hf.space'
ENV SCICO_API_URL=None

# Change the working directory
WORKDIR /app/src

# Run a shell
CMD ["bash"]

# # Run the uvicorn server in the conda environment
# CMD ["conda", "run", "--no-capture-output", "-n", "docker_env", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]